version: "3.7"
services:
  db:
    container_name: db
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db
    environment:
      - SQLITE3_DB=sample.db

  php:
    container_name: api
    image: api
    build:
      context: ./api/
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000
    volumes:
      - ./api:/api
    environment:
      - DB_SERVER=db
      - DATABASE_URL=db
      - DB_PORT=3306
      - DB_NAME=app
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - default

  app:
    container_name: app
    image: app
    stdin_open: true
    build:
      context: ./app/
      dockerfile: ./docker/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - './app:/app'
      - '/app/node_modules'
    links:
      - php
      - nginx
    environment:
      - NODE_ENV=development
    depends_on:
      - php
      - nginx

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./api/docker/nginx
      dockerfile: ./Dockerfile
    links:
      - php
    volumes:
      - "./api/public:/var/www/api/public"
    ports:
      - 8080:80
      - 444:443
    environment:
      - API_HOST=php
      - API_PORT=9000