doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_sqlite'
                url: '%env(resolve:DATABASE_URL)%'

    orm:
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/'
                prefix: 'PhoneNumberCategotization\'
                alias: PhoneNumberCategotization
