doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%kernel.project_dir%/db/sample.db"


    orm:
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/'
                prefix: 'PhoneNumberCategotization\'
                alias: PhoneNumberCategotization
