framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        default_bus: authless.bus
        buses:
            authless.bus:
                middleware:
                    - validation
                    - doctrine_transaction

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': async